config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#index"

  post '#', to: 'pages#create', as: 'new_gif'
  delete 'delete/:id', to: 'pages#delete', as: 'delete_gif'
  get 'edit/:id', to: 'pages#edit_gif', as: 'edit_gif'
  post 'edit', to: 'pages#edit_video_gif', as: 'edit_video_gif'
  post 'update', to: 'pages#update', as: 'update_gif'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gif.rb
class Gif < ApplicationRecord
  has_one_attached :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  rescue_from Exception, with: :exception

  def index
    @gifs = Gif.all
  end

  def create
    ilist = Magick::ImageList.new
    gif_params[:files].each do |i|
      ilist.read i.path
    end
    ilist.each do |image|
      image = image.resize_to_fill!(gif_params[:width].to_i, gif_params[:height].to_i)
    end
    ilist.iterations = 0
    ilist.delay = gif_params[:delay]
    ilist.ticks_per_second = gif_params[:ticks_per_second]

    file = Tempfile.new
    file.binmode
    file.write ilist.to_blob { |attrs| attrs.format = 'gif' }
    file.open

    gif = Gif.create(name: gif_params[:name])
    gif.image.attach(io: file, filename: "#{gif_params[:name]}.gif")

    file.close(unlink_now: true)

    redirect_to root_path
  end

  def edit_gif
    code = rand(36**15).to_s(36)
    @images_blob = []

    @gif = Gif.find(params[:id])

    ilist = Magick::ImageList.new(ActiveStorage::Blob.service.send(:path_for, @gif.image.key))
    images = ilist.to_a

    images.each_with_index do |image, i|
      file = Tempfile.new
      file.binmode
      file.write image.to_blob
      file.open
      blob = ActiveStorage::Blob.create_after_upload!(io: file, filename: "#{code}-#{i}.jpg")
      file.close(unlink_now: true)

      @images_blob << blob
    end

    @name = @gif.name
    @delay = ilist.delay
    @ticks_per_second = ilist.ticks_per_second
    @width = ilist.first.columns
    @height = ilist.first.rows

    render 'edit'
  end

  def edit_video_gif
    code = rand(36**15).to_s(36)
    @images_blob = []

    video = FFMPEG::Movie.new(gif_params[:file].path.to_s)
    video.screenshot("tmp/#{code}-%d.jpg", { vframes: 999999, frame_rate: gif_params[:fps], resolution: "#{gif_params[:width]}x#{gif_params[:height]}"}, validate: false)
    Dir["tmp/#{code}-*.jpg"].count.times do |i|
      path = Rails.root.join("tmp","#{code}-#{i+1}.jpg")
      file = File.open(path, "rb")
      blob = ActiveStorage::Blob.create_after_upload!(io: file, filename: "#{code}-#{i}.jpg")
      File.delete(path)

      @images_blob << blob
    end

    @name = gif_params[:name]
    @delay = gif_params[:delay]
    @ticks_per_second = gif_params[:ticks_per_second]
    @width = gif_params[:width]
    @height = gif_params[:height]

    render 'edit'
  end

  def update
    image_hash = []
    count = 0
    sort = 0
    gif_params[:individual_images].each do |e|
      if !e[0].include?("index-")
        gif_params[:individual_images].each do |f|
          sort = f[1] if f[0].include?(e[0]) && f[0].include?("index-")
        end
        image_hash << {image: e[0], checked: e[1], sort: sort}
        count += 1 if e[1] == "1"
      end
    end
    if count <= 0
      redirect_to root_path
      return
    end
    image_hash = image_hash.sort_by { |h| h[:sort] }

    ilist = Magick::ImageList.new
    image_hash.each do |image|
      ilist.read ActiveStorage::Blob.service.send(:path_for, image[:image]) if image[:checked] == "1"
      ActiveStorage::Blob.find_by(key: image[:image]).purge
    end

    ilist.each do |image|
      image = image.resize_to_fill!(gif_params[:width].to_i, gif_params[:height].to_i)
    end
    ilist.iterations = 0
    ilist.delay = gif_params[:delay]
    ilist.ticks_per_second = gif_params[:ticks_per_second]

    file = Tempfile.new
    file.binmode
    file.write ilist.to_blob { |attrs| attrs.format = 'gif' }
    file.open

    gif_params[:id].blank? ? @gif = Gif.new : @gif = Gif.find(gif_params[:id])
    @gif.update(name: gif_params[:name])
    @gif.image.purge if @gif.image.attached?
    @gif.image.attach(io: file, filename: "#{gif_params[:name]}.gif")
    @gif.save

    file.close(unlink_now: true)

    redirect_to root_path
  end

  def delete
    Gif.find(params[:id]) do |gif|
      gif.image.purge
      gif.destroy
    end

    redirect_to root_path
  end

  private
  def gif_params
    params.require(:gif).permit(:id, :name, {files: []}, {individual_images: {}}, :delay, :ticks_per_second, :width, :height, :file, :fps)
  end

  def exception
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GifTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.slim
h1 Edit Gif
hr
= simple_form_for :gif, url: update_gif_path, methods: :post do |f|
  = f.hidden_field :id, value: @gif.id unless @gif.blank?
  = f.simple_fields_for :individual_images do |ff|
    - @images_blob.each_with_index do |blob, i|
      = image_tag blob
      = ff.input "#{blob.key}", as: :boolean, input_html: {checked: true}
      = ff.input "index-#{blob.key}", as: :integer, input_html: {value: i}
  hr
  = f.input :name, input_html: {value: @name}
  = f.input :delay, as: :integer, input_html: {value: @delay}
  = f.input :width, as: :integer, input_html: {value: @width}
  = f.input :height, as: :integer, input_html: {value: @height}
  = f.input :ticks_per_second, as: :integer, input_html: {value: @ticks_per_second}
  = f.submit
hr
= link_to "back", root_path

app/views/pages/index.html.slim
h1 Gif Test
hr
h2 create gif by selecting multiple files(gif, image, video etc..) with rmagick
h4 video will take some time, so it is better to use ffmpeg
hr
= simple_form_for :gif, url: new_gif_path, methods: :post, html: { multipart: true } do |f|
  = f.input :name, input_html: {value: 'giftest'}
  = f.label :files
  = f.file_field :files, multiple: true
  = f.input :width, as: :integer, input_html: {value: 300}
  = f.input :height, as: :integer, input_html: {value: 400}
  = f.input :delay, as: :integer, input_html: {value: 20}, hint: "if 100 as a tick for a second,eg 20 = 1/5 of a second for each transition"
  = f.input :ticks_per_second, as: :integer, input_html: {value: 100}, hint: "100 as the default value"
  = f.submit "Create gif with image or gif files"
hr
h2 create gif by selecting a video file with ffmpeg, faster version for video by setting fps
h4 gif file can also be uploaded but not suitable
hr
= simple_form_for :gif, url: edit_video_gif_path, method: :post do |f|
  = f.input :name, input_html: {value: 'giftest'}
  = f.label :file
  = f.file_field :file
  = f.input :fps, input_html: {value: 2}, hint: "default generates 2 screenshots per second"
  = f.input :width, as: :integer, input_html: {value: 300}
  = f.input :height, as: :integer, input_html: {value: 400}
  = f.input :delay, as: :integer, input_html: {value: 20}, hint: "if 100 as a tick for a second,eg 20 = 1/5 of a second for each transition"
  = f.input :ticks_per_second, as: :integer, input_html: {value: 100}, hint: "100 as the default value"
  = f.submit "Create gif with video file"
hr
h2 list of created gifs
hr
- @gifs.each do |gif|
  h3 = gif.name
  h3 = link_to 'delete', delete_gif_path(gif.id), method: :delete
  h3 = link_to 'edit', edit_gif_path(gif.id)
  h3
    a href="#{url_for(gif.image)}" download="#{gif.name}" download
  = image_tag gif.image